pds : http://116.236.192.108:58888
#youdu_users: "胡彪_张静文_李瑞霞_张迎盈_孙励_王烨权"
youdu_users: "张静文"
weixin_toparty: 2
Gaolu:
  username: lxl
  password: 123456

用例配置:
  表单关联: "测试表02 金属结构声屏障现场质量检查记录表(JL)"
  工程模板:
      dataTemplateItemId1: "测试表02 金属结构声屏障现场质量检查记录表(JL)"
      dataTemplateItemId2: "测试表4.4.2-6 软土地基刚性桩现场质量检验表(SG)"
      dataTemplateItemId3: "测试表4.5.2-1 加筋工程土工合成材料现场质量检验表(SG)"
      dataTemplateItemId4: "测试表4.5.2-2 隔离工程土工合成材料现场质量检验表(SG)"
      dataTemplateItemId5: "测试表4.5.2-3 过滤排水工程土工合成材料现场质量检验表(SG)"